# Generated by Django 5.2.6 on 2025-10-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HamtiRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('تاریخ', models.CharField(blank=True, max_length=50, null=True)),
                ('شهر', models.CharField(blank=True, max_length=100, null=True)),
                ('منطقه', models.CharField(blank=True, max_length=100, null=True)),
                ('کد_سفارش', models.CharField(max_length=50, unique=True)),
                ('نوع_کسب_کار', models.CharField(blank=True, max_length=100, null=True)),
                ('حوزه_تخصصی', models.CharField(blank=True, max_length=100, null=True)),
                ('نام_واحد_تجاری', models.CharField(blank=True, max_length=255, null=True)),
                ('آدرس', models.TextField(blank=True, null=True)),
                ('شماره_مشتری', models.CharField(blank=True, max_length=255, null=True)),
                ('نام_مدیریت', models.CharField(blank=True, max_length=100, null=True)),
                ('کارشناس_پیگیری', models.CharField(blank=True, max_length=100, null=True)),
                ('مبلغ_توافق_شده', models.CharField(blank=True, max_length=100, null=True)),
                ('مبلغ_فاکتور_شده', models.CharField(blank=True, max_length=100, null=True)),
                ('مبلغ_واریز_شده', models.CharField(blank=True, max_length=100, null=True)),
                ('قسط_اول', models.CharField(blank=True, max_length=100, null=True)),
                ('قسط_دوم', models.CharField(blank=True, max_length=100, null=True)),
                ('نتیجه_تماس', models.CharField(blank=True, max_length=255, null=True)),
                ('وضعیت_درخواست_مشتری', models.CharField(blank=True, max_length=255, null=True)),
                ('پیام_رسان_نمونه_کار', models.CharField(blank=True, max_length=255, null=True)),
                ('وضعیت_ارسال', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
