# Generated by Django 5.2.6 on 2025-10-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamtirecord',
            name='کد_سفارش',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
