# Generated by Django 5.2.6 on 2025-10-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_alter_hamtirecord_کد_سفارش'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamtirecord',
            name='توضیحات_نمونه_کار',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hamtirecord',
            name='زمان_تمدید',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hamtirecord',
            name='ساعت_تماس_بعدی',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hamtirecord',
            name='مبدا_شماره',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hamtirecord',
            name='مقصد',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hamtirecord',
            name='پیغام_مدیر',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
