# Generated by Django 5.2.6 on 2025-10-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_hamtirecord_توضیحات_نمونه_کار_hamtirecord_زمان_تمدید_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamtirecord',
            name='شماره_مشتری',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='hamtirecord',
            name='مبدا_شماره',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hamtirecord',
            name='مقصد',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hamtirecord',
            name='نام_مدیریت',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
