# Generated by Django 5.2.6 on 2025-10-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_alter_hamtirecord_شماره_مشتری_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamtirecord',
            name='مبدا_شماره',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='hamtirecord',
            name='پیغام_مدیر',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
