# Generated by Django 5.2.6 on 2025-09-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('manager', 'Manager'), ('sales', 'Sales'), ('tech', 'Tech')], max_length=50, unique=True)),
            ],
        ),
    ]
