# Generated by Django 5.2.6 on 2025-10-23 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('date', models.DateField(verbose_name='تاریخ فاکتور')),
                ('business_name', models.CharField(max_length=200, verbose_name='نام صنف')),
                ('agency_manager', models.CharField(max_length=200, verbose_name='مدیریت')),
                ('license_number', models.CharField(default='14030455', verbose_name='شماره مجوز')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone_numbers', models.TextField(verbose_name='شماره تلفن')),
                ('description', models.TextField(blank=True, default='-', null=True, verbose_name='توضیحات')),
                ('font_size', models.IntegerField(choices=[(8, '8 pt'), (9, '9 pt'), (10, '10 pt'), (11, '11 pt'), (12, '12 pt')], default=10, verbose_name='اندازه فونت (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('paye', 'پکیج پایه'), ('almas', 'پکیج الماس')], max_length=50, verbose_name='نام خدمات')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ کل (ریال)')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'خدمات',
            },
        ),
    ]
