# Generated by Django 5.2.6 on 2025-09-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('date', models.DateField(verbose_name='تاریخ فاکتور')),
                ('business_name', models.CharField(max_length=200, verbose_name='نام کسب و کار')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=100, verbose_name='شماره تماس')),
                ('services', models.TextField(verbose_name='شرح خدمات (هر خدمت در یک خط جداگانه)')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ کل (ریال)')),
                ('agency_manager', models.CharField(default='ابوالفضل ناطق', max_length=100, verbose_name='مدیریت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
    ]
