# Generated by Django 5.2.6 on 2025-09-28 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='services',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='license_number',
            field=models.CharField(default=12, max_length=100, verbose_name='شماره مجوز'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='business_name',
            field=models.CharField(max_length=200, verbose_name='نام صنف'),
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='نام خدمات')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ (ریال)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='invoice.invoice')),
            ],
        ),
    ]
