# Generated by Django 5.2.6 on 2025-10-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='send_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت ارسال'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='font_size',
            field=models.IntegerField(choices=[(6, '6 pt'), (7, '7 pt'), (8, '8 pt'), (9, '9 pt'), (10, '10 pt'), (11, '11 pt'), (12, '12 pt'), (13, '13 pt'), (14, '14 pt')], default=10, verbose_name='اندازه فونت (PDF)'),
        ),
    ]
