# Generated by Django 5.2.6 on 2025-09-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_address_remove_invoice_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
