# Generated by Django 5.2.6 on 2025-11-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_send_time_alter_invoice_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='font_size',
            field=models.IntegerField(choices=[(6, '6 pt'), (7, '7 pt'), (8, '8 pt'), (9, '9 pt'), (10, '10 pt'), (11, '11 pt'), (12, '12 pt'), (13, '13 pt'), (14, '14 pt')], default=11, verbose_name='اندازه فونت (PDF)'),
        ),
    ]
