# Generated by Django 5.2.6 on 2025-10-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_serviceitem_options_serviceitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='service_name',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='agency_manager',
            field=models.CharField(max_length=100, verbose_name='مدیریت'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='license_number',
            field=models.CharField(default='14030455', max_length=100, verbose_name='شماره مجوز'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
    ]
