# Generated by Django 5.2.6 on 2025-10-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_remove_serviceitem_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='phone_number',
            field=models.CharField(default='_', max_length=20, verbose_name='شماره تلفن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service_name',
            field=models.CharField(choices=[('paye', 'پکیج پایه'), ('almas', 'پکیج الماس'), ('noghre', 'پکیج نقره'), ('plat', 'پکیج پلاتین')], default='-', max_length=50, verbose_name='نام خدمت'),
            preserve_default=False,
        ),
    ]
