# Generated by Django 5.2.6 on 2025-10-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_address_invoice_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'verbose_name': 'خدمات', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(default=12, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ کل (ریال)'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='service_name',
            field=models.CharField(choices=[('paye', 'پکیج پایه'), ('almas', 'پکیج الماس')], max_length=50, verbose_name='نام خدمات'),
        ),
    ]
