# Generated by Django 5.2.6 on 2025-10-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_serviceitem_options_invoice_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ واحد (ریال)'),
        ),
    ]
