# Generated by Django 5.2.6 on 2025-10-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_invoice_description_alter_serviceitem_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='description',
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='description',
            field=models.CharField(blank=True, choices=[('خدمت اول', 'خدمت اول'), ('خدمت دوم', 'خدمت دوم'), ('خدمت سوم', 'خدمت سوم'), ('خدمت ویژه', 'خدمت ویژه')], help_text='یکی از گزینه\u200cهای از پیش تعریف\u200cشده را انتخاب کنید.', max_length=50, null=True, verbose_name='نوع خدمت'),
        ),
    ]
