# Generated by Django 5.2.6 on 2025-10-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_serviceitem_options_remove_invoice_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='description',
            field=models.CharField(blank=True, help_text='می\u200cتوانید متن دلخواه تایپ یا از مقادیر قبلی انتخاب کنید.', max_length=100, null=True, verbose_name='توضیحات (قابل تایپ یا انتخاب)'),
        ),
    ]
