# Generated by Django 5.2.6 on 2025-10-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_serviceitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='description',
            field=models.TextField(blank=True, help_text='هر توضیح را در یک خط جداگانه بنویسید.', null=True, verbose_name='توضیحات (حداکثر ۱۰ مورد، هر مورد در یک خط جدا)'),
        ),
    ]
