# Generated by Django 5.2.6 on 2025-10-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_serviceitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کلی'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='description',
            field=models.TextField(blank=True, help_text='هر مورد را در یک خط بنویسید (مثلاً:\n1- خدمت اول\n2- خدمت دوم)', null=True, verbose_name='توضیحات (هر مورد در یک خط جدا)'),
        ),
    ]
