# Generated by Django 5.2.6 on 2025-10-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_invoice_description_alter_serviceitem_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'verbose_name': 'خدمات', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(default=12, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ کل (ریال)'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
